name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  env:
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add SSH key
        run: |
          echo "$PRIVATE_KEY" > private-key.pem
          chmod 600 private-key.pem
          eval "$(ssh-agent -s)"
          ssh-add private-key.pem

      - name: Push changes to private repository
        run: |
          git remote add private git@github.com:EpitechWebAcademiePromo2024/W-PRO-250-LYN-3-2-projetlibre-victor.imbo.git
          git push private HEAD:main
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
